"""Re-plan models for V7 Task 166a.

这些模型只描述弧后评估与 draft proposal。人工确认、应用和回滚由
Task 166b 负责，本模块不表达任何自动执行语义。
"""

from __future__ import annotations

from datetime import datetime
from typing import Any, Literal

from pydantic import BaseModel, Field

ReplanProposalStatus = Literal["draft", "approved", "rejected", "applied"]
ReplanActionTargetType = Literal["arc_plan", "plot_thread", "style_constraint"]
ArcOutcomeRiskLevel = Literal["none", "low", "medium", "high"]
PlanningConstraintType = Literal["style_constraint", "planning_constraint"]
PlanningConstraintStatus = Literal["active", "archived"]


class ReplanAction(BaseModel):
    """A proposed future-planning change generated by Task 166a."""

    action_id: str
    proposal_id: str
    action_order: int = Field(ge=0)
    target_type: ReplanActionTargetType
    target_id: str = ""
    field: str
    old_value: Any = None
    new_value: Any = None
    reason: str
    evidence: dict[str, Any] = Field(default_factory=dict)
    created_at: datetime = Field(default_factory=datetime.now)


class ReplanProposal(BaseModel):
    """Draft proposal produced from an arc outcome evaluation."""

    proposal_id: str
    project_id: str
    source_arc_index: int | None = None
    source_start_chapter: int | None = None
    source_end_chapter: int | None = None
    status: ReplanProposalStatus = "draft"
    summary: str = ""
    evidence: dict[str, Any] = Field(default_factory=dict)
    created_at: datetime = Field(default_factory=datetime.now)
    updated_at: datetime = Field(default_factory=datetime.now)
    actions: list[ReplanAction] = Field(default_factory=list)


class ArcOutcomeEvaluation(BaseModel):
    """Read-only evaluation of planned arc goals against generated facts."""

    project_id: str
    has_skeleton: bool
    source_arc_id: str | None = None
    source_arc_index: int | None = None
    source_start_chapter: int | None = None
    source_end_chapter: int | None = None
    arc_goal: str = ""
    risk_level: ArcOutcomeRiskLevel = "none"
    summary: str = ""
    evidence: dict[str, Any] = Field(default_factory=dict)
    unopened_threads: list[str] = Field(default_factory=list)
    unresolved_threads: list[str] = Field(default_factory=list)
    metric_warnings: list[str] = Field(default_factory=list)
    style_debt_signals: list[str] = Field(default_factory=list)
    evaluated_at: datetime = Field(default_factory=datetime.now)


class PlanningConstraint(BaseModel):
    """Future-planning constraint created by approved re-plan actions."""

    constraint_id: str
    project_id: str
    source_proposal_id: str
    source_action_id: str
    target_id: str = ""
    constraint_type: PlanningConstraintType
    content: str
    reason: str = ""
    status: PlanningConstraintStatus = "active"
    created_at: datetime = Field(default_factory=datetime.now)


class ReplanApplicationResult(BaseModel):
    """Result returned after applying one approved proposal."""

    proposal_id: str
    project_id: str
    applied_action_ids: list[str] = Field(default_factory=list)
    applied_by: str = ""
    applied_at: datetime = Field(default_factory=datetime.now)
